### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by nhasanit** [jeffvestal/ElasticDocs_GPT#4]
I am receiving the following error when trying to query something using the ElasticGPT python app.

`IndexError: list index out of range`

This is what the app returns in the Traceback

Traceback (most recent call last):
```
  File "/home/user/ElasticDocs_GPT/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/user/ElasticDocs_GPT/elasticdocs_gpt.py", line 110, in <module>
    resp, url = search(query)
  File "/home/user/ElasticDocs_GPT/elasticdocs_gpt.py", line 77, in search
    body = resp['hits']['hits'][0]['fields']['body_content'][0]
```

I have set this up exactly from the instructions on the blog article. I have also attempted different versions of urllib3 and requests libraries but that did not change anything. Any assistance would be much appreciated.

**Comment by jeffvestal** [comment]
Hi @nhasanit The error means there are no hits coming back from the query. 

I would try two things. 
1. in Devtools Console run `GET <index_name>/_search` and check which field actually has the dense vectors. Its possible the field name changed between the current version and when I wrote the blog. If it's just in another field name, you can update the python script to point to that field. 
2. Assuming there are vectors in some field, run `_mapping` to check that the field containing the vectors is of type `dense_vector`

**Comment by nhasanit** [comment]
hi @jeffvestal 

Thanks for the reply. 

I looked at the mappings and from the blog article it looks like the field that has the dense_vector mapping is title_vector and not title:

```
          "title-vector": {
          "type": "dense_vector",
          "dims": 768,
          "index": true,
          "similarity": "dot_product"
```

I tried changing line 68
`fields = ["title", "body_content", "url"]`
to:
`fields = ["title-vector", "body_content", "url"]`

Neither is returning any results for the query "Show me the API call for Reindex"

I have run the following search to make sure all of the data looks correct
```
GET /_search
{
  "query": {
    "query_string": {
      "query": "Reindex API",
      "default_field": "title"
    }
  }
}
```

I do not see anything wrong with it so I am not sure what I am missing here. 

I have attached my mappings, search results, and the python code I am currently using. Let me know if there is anything else I can try. 






[elasticdocs_gpt_py.txt](https://github.com/jeffvestal/ElasticDocs_GPT/files/12109173/elasticdocs_gpt_py.txt)
[mapping.txt](https://github.com/jeffvestal/ElasticDocs_GPT/files/12109174/mapping.txt)
[search.txt](https://github.com/jeffvestal/ElasticDocs_GPT/files/12109175/search.txt)

**Comment by jeffvestal** [comment]
Hey, thanks for the links
Are you running 8.8.1 by chance? I think something changed or got reverted with the auto created dense_vector mapping. I'm trying to run it down this morning. 

In the mean time, in the search results I see the field `elastic-docs_title-vector` contains embeddings 
```
          "elastic-docs_title-vector": [
            -0.00014185166219249368,
            0.006422760896384716,
            0.024252265691757202,
            -0.05329488217830658,
...
```

however that field has the mapping :
```
        "elastic-docs_title-vector": {
          "type": "float"
        },
```
which is just what dynamic mapping does since ES thinks its an array of floats. 

While I track down what happened you can try the following (sorry its going to be a few steps)

1. delete your existing index through the enterprise search UI, that should delete the index and crawler settings...
2. redo the steps just as you did before, however, in the blog there is a step that shows you a POST command to get the `dense_vector` mapping BEFORE you configure the crawler. It says you won't have to do this post 8.8 but, again, something happened. You'll have to modify that POST command to have the field that the embeddings are now landing in 
```
POST search-elastic-docs/_mapping
{
  "properties": {
    "elastic-docs_title-vector": {
      "type": "dense_vector",
      "dims": 768,
      "index": true,
      "similarity": "dot_product"
    }
  }
}
```
3. finish setting everything up and run the crawler. After it runs verify the mapping for `elastic-docs_title-vector` is set to `dense_vector` still AND when you run `_search` it contains embeddings
4. Update the `query` and `knn` sections of the script
```
    query = {
        "bool": {
            "must": [{
                "match": {
                    "title": {
                        "query": query_text,
                        "boost": 1
                    }
                }
            }],
            "filter": [{
                "exists": {
                    "field": "elastic-docs_title-vector"
                }
            }]
        }
    }

    knn = {
        "field": "elastic-docs_title-vector",
        "k": 1,
        "num_candidates": 20,
        "query_vector_builder": {
            "text_embedding": {
                "model_id": "sentence-transformers__all-distilroberta-v1",
                "model_text": query_text
            }
        },
        "boost": 24
    }

   fields = ["elastic-docs_title-vector", "body_content", "url"]
```

Let me know how that goes

**Comment by nhasanit** [comment]
@jeffvestal that worked! thank you so much for your help. On another note, I was thinking of integrating this chatbot with Workplace search. Would that work? I was thinking of reindexing a workplace search index with the same inference pipeline and then when searching, search an array of indices instead of just one. 

Oh and to answer your question, I was using 8.8.2

**Comment by nhasanit** [comment]
https://github.com/jeffvestal/ElasticDocs_GPT/issues/4#issuecomment-1643979013

This solved my issue.
